/.autofs/tools/spack/var/spack/environments/default-nlp-x86_64-24072401/.spack-env/view/lib/python3.11/site-packages/jupyter_client/connect.py:20: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
given by the platformdirs library.  To remove this warning and
see the appropriate new directories, set the environment variable
`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
The use of platformdirs will be the default in `jupyter_core` v6
  from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
/home/rgg2706/Multimodal-Sentiment-Analysis/Models/DMLAN/src/data_utils.py:46: ResourceWarning: unclosed file <_io.TextIOWrapper name='Models/util_models/glove.twitter.27B/glove.twitter.27B.200d.txt' mode='r' encoding='utf-8'>
  word_vec = load_word_vec(fname, word2idx=word2idx)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/DMLAN/src/data_utils.py", line 142, in __read_data__
    image = image_process(image_path, transform)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/DMLAN/src/data_utils.py", line 57, in image_process
    image = Image.open(image_path).convert('RGB')
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/.autofs/tools/spack/var/spack/environments/default-nlp-x86_64-24072401/.spack-env/view/lib/python3.11/site-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './Datasets/MVSA-MTS/images-indexed/706.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/DMLAN/src/train.py", line 71, in <module>
    ins = Instructor(opt)
          ^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/DMLAN/src/instructor.py", line 53, in __init__
    mvsa_dataset = MVSADatasetReader(transform, dataset=opt.dataset, 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/DMLAN/src/data_utils.py", line 185, in __init__
    train_data, train_classes = MVSADatasetReader.__read_data__(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/DMLAN/src/data_utils.py", line 146, in __read_data__
    image = image_process(image_path_fail, transform)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/DMLAN/src/data_utils.py", line 57, in image_process
    image = Image.open(image_path).convert('RGB')
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/.autofs/tools/spack/var/spack/environments/default-nlp-x86_64-24072401/.spack-env/view/lib/python3.11/site-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './Datasets/MVSA-MTS/images-indexed/0default.jpg'
