/Users/ronengold/Library/Mobile Documents/com~apple~CloudDocs/Repositories/multimodal-sentiment-analysis-main/Models/DMLAN/src/data_utils.py:46: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/ronengold/Datasets/util_models/glove.twitter.27B/glove.twitter.27B.200d.txt' mode='r' encoding='utf-8'>
  word_vec = load_word_vec(fname, word2idx=word2idx)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/opt/homebrew/Caskroom/miniconda/base/envs/ml/lib/python3.13/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/opt/homebrew/Caskroom/miniconda/base/envs/ml/lib/python3.13/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=Inception_V3_Weights.IMAGENET1K_V1`. You can also use `weights=Inception_V3_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/Users/ronengold/Library/Mobile Documents/com~apple~CloudDocs/Repositories/multimodal-sentiment-analysis-main/Models/DMLAN/src/train.py", line 74, in <module>
    ins.run()
    ~~~~~~~^^
  File "/Users/ronengold/Library/Mobile Documents/com~apple~CloudDocs/Repositories/multimodal-sentiment-analysis-main/Models/DMLAN/src/instructor.py", line 161, in run
    loss = criterion(outputs, targets)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ml/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ml/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ml/lib/python3.13/site-packages/torch/nn/modules/loss.py", line 1293, in forward
    return F.cross_entropy(
           ~~~~~~~~~~~~~~~^
        input,
        ^^^^^^
    ...<4 lines>...
        label_smoothing=self.label_smoothing,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ml/lib/python3.13/site-packages/torch/nn/functional.py", line 3479, in cross_entropy
    return torch._C._nn.cross_entropy_loss(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        input,
        ^^^^^^
    ...<4 lines>...
        label_smoothing,
        ^^^^^^^^^^^^^^^^
    )
    ^
RuntimeError: Expected target size [24, 3], got [24]
/opt/homebrew/Caskroom/miniconda/base/envs/ml/lib/python3.13/tempfile.py:936: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/13/_kqy4dm103x9f8nk0jq0nbmr0000gn/T/tmpuip7vbfj'>
  _warnings.warn(warn_message, ResourceWarning)
